### ISSUE TITLE
Try to compile on Ubuntu

### ISSUE THREAD

**Issue by geotyper** [electromaggot/HelloVulkanSDL#2]
Hello,

try to run this project under Ubuntu.
But have some problems:
![Screenshot at 2022-02-18 13-27-37](https://user-images.githubusercontent.com/30755433/154665743-7d1f30f4-f221-4d8c-8366-636322055174.png)
first this error, if change code by init temp array with 0, program compile(have also some problems with ImGui, but if use ImGui from git all compiles).
But program crash at start (use SDL backend), at trying ranking physical device.
Interesting that if set breakpoints, first breakpoint is:
![Screenshot at 2022-02-18 13-23-14](https://user-images.githubusercontent.com/30755433/154666644-bd8e3fbe-d907-408d-b729-2aed596cd14e.png)
another words program come to the end of function without execute it
VkPhysicalDevice GraphicsDevice::selectGPU(VkInstance& instance, VkSurfaceKHR& surface,DeviceSelectionMethod choice) 
and only after return state begin to execute this function from the beginnig, and crash on function: string DeviceRanking::RankDevices(VkPhysicalDevice devices[], int nDevices, int rankedIndices[])

crash at this point iPass=0 and IDevice=0:
![Screenshot at 2022-02-18 13-51-37](https://user-images.githubusercontent.com/30755433/154669133-417a44cb-e36a-481f-9e57-64c4bdc49eb0.png)

thsi is log:
![Screenshot at 2022-02-18 13-50-09](https://user-images.githubusercontent.com/30755433/154668916-29fcc8ec-955d-48f1-ad49-ea37d86f3e7b.png)

**Comment by geotyper** [comment]
about first error change code to this:
![Screenshot at 2022-02-18 13-43-25](https://user-images.githubusercontent.com/30755433/154667806-3db1ccfa-faae-4f22-a4e1-c93ca47ce6a0.png)

**Comment by geotyper** [comment]
have also error with ImGui (undefines reference to MainGUI (DearImGui&)
![Screenshot at 2022-02-18 13-44-43](https://user-images.githubusercontent.com/30755433/154668000-5f2eff7e-fcaa-48ea-ab2c-6918325bdf28.png)
but now comment it/ because project crash earlier

**Comment by geotyper** [comment]
found that if comment line of memset
![Screenshot at 2022-02-19 20-19-43](https://user-images.githubusercontent.com/30755433/154811673-c808c48d-fb1b-4504-9f1f-16905ec0f1a7.png)
program init and go to main loop.
but need to solve preRender for MainGui:
![Screenshot at 2022-02-19 20-41-13](https://user-images.githubusercontent.com/30755433/154812454-48b570bf-b9d8-4077-8c24-944ae13a4430.png)
It looks like ImGui not init and can't solve preRender(MainGUI, platform);

**Comment by electromaggot** [comment]
Greetings @geotyper, I'm sorry to follow up so late (I was consumed with other work)...
I now have an Ubuntu system that, thanks to your inspiration, I would like to get this project running on.  From your screenshots, is this VS Code you're using to run it?  Was there additional build setup or scripts or CMake that you used to build your project?
If so and these are in your fork, would you mind committing your changes that I could clone and build?  Then I can test/reproduce the bugs you've seen, incorporate your fixes (perhaps if you'd like to submit PRs?), I can make additional fixes of my own, and finally officially support Linux.  I'd like to get back to further advancing this project with some new features too.
Thanks for submitting all this and please let me know your thoughts!

**Comment by electromaggot** [comment]
I added support for building on Ubuntu (last year! 😬) and did incorporate the changes you suggested!  Thanks being the catalyst on that.  Closing this issue (finally!).
